# Generated by Django 3.1.1 on 2020-10-04 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('std_mgmt_sys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.CharField(max_length=25)),
                ('maths', models.CharField(max_length=25)),
                ('science', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Tutorials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('teacher', models.CharField(max_length=25)),
                ('date_submission', models.IntegerField()),
            ],
        ),
    ]
