# Generated by Django 3.1.1 on 2020-10-05 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('std_mgmt_sys', '0006_auto_20201005_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=25)),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='std_mgmt_sys.teachers')),
            ],
        ),
    ]
