# Generated by Django 3.1.1 on 2020-10-11 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('std_mgmt_sys', '0008_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='profile_photo',
            field=models.ImageField(default='sanjog.jpg', upload_to='book_photos'),
        ),
    ]
